config/routes.rb
Calculator::Application.routes.draw do

  match 'dashboard' => 'front#dashboard', :as => :dashboard, via: [:get, :post, :patch]

  root 'front#dashboard'

end

app/models/investment.rb
class Investment < ActiveRecord::Base
  validates :square_feet, :cost_of_property, :sale_value_of_property, :numericality => {:greater_than => 0.0}

  def sale_value_of_property=(val)
    self[:return_of_investment] = (self.cost_of_property.to_f - val.to_f)/self.cost_of_property.to_f * 100
    self[:sale_value_of_property] = val
  end

  def profit_per_square_feet
    ((self.cost_of_property - self.sale_value_of_property)/self.square_feet).round(2)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/front_controller.rb
class FrontController < ApplicationController
  def dashboard
    @investment = Investment.new
    if request.post?
      @investment = Investment.new(investment_params)
      respond_to do |format|
        if @investment.save
          flash[:notice] = "Return on Investment is: #{@investment.profit_per_square_feet}% with a profit of #{@investment.square_feet} per square feet"
          @investment = Investment.new
          format.html { render action: 'dashboard' }
          format.json {}
        else
          format.html { render action: 'dashboard' }
          format.json { render json: @investment.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def investment_params
      params.require(:investment).permit!
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/front_helper.rb
module FrontHelper
end

app/views/front/dashboard.html.erb
<div class="container pt60">
<h1>Return on Investment</h1>

<%= form_for @investment, :url => dashboard_path do |f| %>

  <div class="control-group">
    <%= f.label :square_feet, :class => "control-label" %>
    <div class="controls">
  		<%= f.text_field :square_feet %>
      <% if @investment.errors[:square_feet].any? %>
          <span class="text-error text-message"><%= @investment.errors[:square_feet].first %></span>
      <% end %>
     </div>   
  </div>
  <div class="clearBoth"></div>
  <div class="control-group">
    <%= f.label :cost_of_property, :class => "control-label" %>
    <div class="controls">
    <%= f.text_field :cost_of_property %>
        <% if @investment.errors[:cost_of_property].any? %>
            <span class="text-error text-message"><%= @investment.errors[:cost_of_property].first %></span>
        <% end %>
     </div>   
  </div>
  <div class="clearBoth"></div>
  <div class="control-group">
    <%= f.label :sale_value_of_property, :class => "control-label" %>
    <div class="controls">
	    <%= f.text_field :sale_value_of_property %>
	        <% if @investment.errors[:sale_value_of_property].any? %>
	            <span class="text-error text-message"><%= @investment.errors[:sale_value_of_property].first %></span>
	        <% end %>
    </div>    
  </div>
  <div class="clearBoth"></div>
  <div class="actions">
    <%= f.submit "Calculate" %>
  </div>
<% end %>

<% if flash[:notice] %>
    <div class="alert-success" id="notice"><%= flash[:notice] %></div>
    <% flash[:notice] = nil %>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Calculator</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>